apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: alv-demo-app-1
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: alv-demo-app-1
spec:
  source:
    git:
      url: https://github.com/sample-accelerators/alv-demo-app-1
      ref:
        branch: main