apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: alv-demo-app-1
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: alv-demo-app-1
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/vudayani-vmw/alv-demo-app
      ref:
        branch: main